name: food_delivery_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cloud_firestore: ^5.1.0
  collection: ^1.18.0
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  flutter:
    sdk: flutter
  flutter_credit_card: ^4.0.1
  intl: ^0.19.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/images_bbq/briskets/
    - lib/images_bbq/desserts/
    - lib/images_bbq/sandwiches/
    - lib/images_bbq/sides/
    - lib/images_bbq/drinks/