// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQl0icdTfiMH90z0LaUPGgsVtq5SzJKgo',
    appId: '1:367089489515:web:da94a1184750e35428832e',
    messagingSenderId: '367089489515',
    projectId: 'finalproject-f31f2',
    authDomain: 'finalproject-f31f2.firebaseapp.com',
    storageBucket: 'finalproject-f31f2.appspot.com',
    measurementId: 'G-P6C1PKDJJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuo_MgIkMl1ClcH62B6IZVQ-ySBs4X6ww',
    appId: '1:367089489515:android:5a6344ff2501931c28832e',
    messagingSenderId: '367089489515',
    projectId: 'finalproject-f31f2',
    storageBucket: 'finalproject-f31f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZbm6_f6W4p_9-ma0cec5jhqrkB_TdSlM',
    appId: '1:367089489515:ios:83f08537fd79af8c28832e',
    messagingSenderId: '367089489515',
    projectId: 'finalproject-f31f2',
    storageBucket: 'finalproject-f31f2.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZbm6_f6W4p_9-ma0cec5jhqrkB_TdSlM',
    appId: '1:367089489515:ios:83f08537fd79af8c28832e',
    messagingSenderId: '367089489515',
    projectId: 'finalproject-f31f2',
    storageBucket: 'finalproject-f31f2.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQl0icdTfiMH90z0LaUPGgsVtq5SzJKgo',
    appId: '1:367089489515:web:faa8eb480a127aec28832e',
    messagingSenderId: '367089489515',
    projectId: 'finalproject-f31f2',
    authDomain: 'finalproject-f31f2.firebaseapp.com',
    storageBucket: 'finalproject-f31f2.appspot.com',
    measurementId: 'G-GXD383QX2T',
  );
}
